#ifndef BASELINER_REGISTER_HPP
#define BASELINER_REGISTER_HPP
#include <baseliner/registry/RegisteringMacros.hpp>
#include <baseliner/registry/Registrars.hpp>

#define BASELINER_REGISTER_STAT(Stat) INNER_BASELINER_REGISTER_STAT(Stat)

#define BASELINER_REGISTER_STOPPING_CRITERION(Stopping) INNER_BASELINER_REGISTER_STOPPING_CRITERION(Stopping)

#define BASELINER_REGISTER_DEFAULT_STATS(DefaultStats) INNER_BASELINER_REGISTER_DEFAULT_STATS(DefaultStats)

#define BASELINER_REGISTER_BENCHMARK(Benchmark) INNER_BASELINER_REGISTER_BENCHMARK(Benchmark)

#define BASELINER_REGISTER_BACKEND(name, Backend) INNER_BASELINER_REGISTER_BACKEND(name, Backend)

#define BASELINER_REGISTER_WORKLOAD(Workload) INNER_BASELINER_REGISTER_WORKLOAD(Workload)

#define BASELINER_REGISTER_WORKLOAD_NAME(Workload, name) INNER_BASELINER_REGISTER_WORKLOAD_NAME(Workload, name)

#define BASELINER_REGISTER_BACKEND_STATS(Stat) INNER_BASELINER_REGISTER_BACKEND_STATS(Stat)

#endif // BASELINER_REGISTRY_REGISTERINGMACROS_HPP